// ddr_rdresp_cmdfifo.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module ddr_rdresp_cmdfifo (
		input  wire [43:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq
		input  wire        clock, //            .clk
		input  wire        sclr,  //            .sclr
		output wire [43:0] q,     // fifo_output.dataout
		output wire [3:0]  usedw, //            .usedw
		output wire        full,  //            .full
		output wire        empty  //            .empty
	);

	ddr_rdresp_cmdfifo_fifo_181_qe2xmpa fifo_0 (
		.data  (data),  //   input,  width = 44,  fifo_input.datain
		.wrreq (wrreq), //   input,   width = 1,            .wrreq
		.rdreq (rdreq), //   input,   width = 1,            .rdreq
		.clock (clock), //   input,   width = 1,            .clk
		.sclr  (sclr),  //   input,   width = 1,            .sclr
		.q     (q),     //  output,  width = 44, fifo_output.dataout
		.usedw (usedw), //  output,   width = 4,            .usedw
		.full  (full),  //  output,   width = 1,            .full
		.empty (empty)  //  output,   width = 1,            .empty
	);

endmodule
