// temperature.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module temperature (
		input  wire       corectl, // corectl.corectl
		input  wire       reset,   //   reset.reset
		output wire [9:0] tempout, // tempout.tempout
		output wire       eoc      //     eoc.eoc
	);

	altera_temp_sense #(
		.DEVICE_FAMILY ("Arria 10")
	) temp_sense_0 (
		.corectl (corectl), //   input,   width = 1, corectl.corectl
		.reset   (reset),   //   input,   width = 1,   reset.reset
		.tempout (tempout), //  output,  width = 10, tempout.tempout
		.eoc     (eoc)      //  output,   width = 1,     eoc.eoc
	);

endmodule
