// uart_rx_dpram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module uart_rx_dpram (
		input  wire [7:0]  data,      //      data.datain
		output wire [7:0]  q,         //         q.dataout
		input  wire [10:0] wraddress, // wraddress.wraddress
		input  wire [10:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	uart_rx_dpram_ram_2port_181_b6f4zwq ram_2port_0 (
		.data      (data),      //   input,   width = 8,      data.datain
		.q         (q),         //  output,   width = 8,         q.dataout
		.wraddress (wraddress), //   input,  width = 11, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 11, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
