// dpram_16bx2048.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module dpram_16bx2048 (
		input  wire [15:0] data,      //      data.datain
		output wire [7:0]  q,         //         q.dataout
		input  wire [10:0] wraddress, // wraddress.wraddress
		input  wire [11:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	dpram_16bx2048_ram_2port_181_nrjdacq ram_2port_0 (
		.data      (data),      //   input,  width = 16,      data.datain
		.q         (q),         //  output,   width = 8,         q.dataout
		.wraddress (wraddress), //   input,  width = 11, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 12, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
