// phyreset.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module phyreset (
		input  wire       clock,              //              clock.clk
		input  wire       reset,              //              reset.reset
		output wire [4:0] rx_analogreset,     //     rx_analogreset.rx_analogreset
		output wire [4:0] rx_digitalreset,    //    rx_digitalreset.rx_digitalreset
		output wire [4:0] rx_ready,           //           rx_ready.rx_ready
		input  wire [4:0] rx_is_lockedtodata, // rx_is_lockedtodata.rx_is_lockedtodata
		input  wire [4:0] rx_cal_busy         //        rx_cal_busy.rx_cal_busy
	);

	altera_xcvr_reset_control #(
		.CHANNELS              (5),
		.PLLS                  (1),
		.SYS_CLK_IN_MHZ        (125),
		.SYNCHRONIZE_RESET     (1),
		.REDUCED_SIM_TIME      (1),
		.TX_PLL_ENABLE         (0),
		.T_PLL_POWERDOWN       (71000),
		.SYNCHRONIZE_PLL_RESET (0),
		.TX_ENABLE             (0),
		.TX_PER_CHANNEL        (0),
		.T_TX_ANALOGRESET      (0),
		.T_TX_DIGITALRESET     (20),
		.T_PLL_LOCK_HYST       (0),
		.EN_PLL_CAL_BUSY       (0),
		.RX_ENABLE             (1),
		.RX_PER_CHANNEL        (1),
		.T_RX_ANALOGRESET      (70040),
		.T_RX_DIGITALRESET     (74000)
	) xcvr_reset_control_0 (
		.clock              (clock),              //   input,  width = 1,              clock.clk
		.reset              (reset),              //   input,  width = 1,              reset.reset
		.rx_analogreset     (rx_analogreset),     //  output,  width = 5,     rx_analogreset.rx_analogreset
		.rx_digitalreset    (rx_digitalreset),    //  output,  width = 5,    rx_digitalreset.rx_digitalreset
		.rx_ready           (rx_ready),           //  output,  width = 5,           rx_ready.rx_ready
		.rx_is_lockedtodata (rx_is_lockedtodata), //   input,  width = 5, rx_is_lockedtodata.rx_is_lockedtodata
		.rx_cal_busy        (rx_cal_busy),        //   input,  width = 5,        rx_cal_busy.rx_cal_busy
		.pll_powerdown      (),                   // (terminated),                                
		.tx_analogreset     (),                   // (terminated),                                
		.tx_digitalreset    (),                   // (terminated),                                
		.tx_ready           (),                   // (terminated),                                
		.pll_locked         (1'b0),               // (terminated),                                
		.pll_select         (1'b0),               // (terminated),                                
		.tx_cal_busy        (5'b00000),           // (terminated),                                
		.pll_cal_busy       (1'b0),               // (terminated),                                
		.tx_manual          (5'b00000),           // (terminated),                                
		.rx_manual          (5'b00000),           // (terminated),                                
		.tx_digitalreset_or (5'b00000),           // (terminated),                                
		.rx_digitalreset_or (5'b00000)            // (terminated),                                
	);

endmodule
