// param_ram4096x8_buf.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module param_ram4096x8_buf (
		input  wire [7:0]  data,      //      data.datain
		output wire [7:0]  q,         //         q.dataout
		input  wire [11:0] wraddress, // wraddress.wraddress
		input  wire [11:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	param_ram4096x8_buf_ram_2port_181_bto3lla ram_2port_0 (
		.data      (data),      //   input,   width = 8,      data.datain
		.q         (q),         //  output,   width = 8,         q.dataout
		.wraddress (wraddress), //   input,  width = 12, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 12, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
