// paramBlkRam2048x72.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module paramBlkRam2048x72 (
		input  wire [71:0] data,      //      data.datain
		output wire [71:0] q,         //         q.dataout
		input  wire [10:0] wraddress, // wraddress.wraddress
		input  wire [10:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	paramBlkRam2048x72_ram_2port_181_uhwgodi ram_2port_0 (
		.data      (data),      //   input,  width = 72,      data.datain
		.q         (q),         //  output,  width = 72,         q.dataout
		.wraddress (wraddress), //   input,  width = 11, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 11, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
