// flash_config_dpram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module flash_config_dpram (
		input  wire [31:0] data,      //      data.datain
		output wire [31:0] q,         //         q.dataout
		input  wire [8:0]  wraddress, // wraddress.wraddress
		input  wire [8:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	flash_config_dpram_ram_2port_181_ih6rdpy ram_2port_0 (
		.data      (data),      //   input,  width = 32,      data.datain
		.q         (q),         //  output,  width = 32,         q.dataout
		.wraddress (wraddress), //   input,   width = 9, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 9, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
