// div10.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module div10 (
		input  wire [15:0] numer,    //  lpm_divide_input.numer
		input  wire [3:0]  denom,    //                  .denom
		input  wire        clock,    //                  .clock
		output wire [15:0] quotient, // lpm_divide_output.quotient
		output wire [3:0]  remain    //                  .remain
	);

	div10_lpm_divide_181_wr7wgzi lpm_divide_0 (
		.numer    (numer),    //   input,  width = 16,  lpm_divide_input.numer
		.denom    (denom),    //   input,   width = 4,                  .denom
		.clock    (clock),    //   input,   width = 1,                  .clock
		.quotient (quotient), //  output,  width = 16, lpm_divide_output.quotient
		.remain   (remain)    //  output,   width = 4,                  .remain
	);

endmodule
