// LPM_9x10.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module LPM_9x10 (
		input  wire [9:0]  dataa,  //  dataa.dataa
		output wire [18:0] result, // result.result
		input  wire [8:0]  datab,  //  datab.datab
		input  wire        clock   //  clock.clk
	);

	LPM_9x10_lpm_mult_181_s6qypzi lpm_mult_0 (
		.dataa  (dataa),  //   input,  width = 10,  dataa.dataa
		.result (result), //  output,  width = 19, result.result
		.datab  (datab),  //   input,   width = 9,  datab.datab
		.clock  (clock)   //   input,   width = 1,  clock.clk
	);

endmodule
