// shuttersync_data55296x16.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module shuttersync_data55296x16 (
		input  wire [15:0] data,      //      data.datain
		output wire [15:0] q,         //         q.dataout
		input  wire [15:0] wraddress, // wraddress.wraddress
		input  wire [15:0] rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	shuttersync_data55296x16_ram_2port_181_mszgv2q ram_2port_0 (
		.data      (data),      //   input,  width = 16,      data.datain
		.q         (q),         //  output,  width = 16,         q.dataout
		.wraddress (wraddress), //   input,  width = 16, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 16, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
