-- fifo320.vhd

-- Generated using ACDS version 18.1 222

library IEEE;
library fifo_181;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fifo320 is
	port (
		data  : in  std_logic_vector(319 downto 0) := (others => '0'); --  fifo_input.datain
		wrreq : in  std_logic                      := '0';             --            .wrreq
		rdreq : in  std_logic                      := '0';             --            .rdreq
		clock : in  std_logic                      := '0';             --            .clk
		aclr  : in  std_logic                      := '0';             --            .aclr
		q     : out std_logic_vector(319 downto 0);                    -- fifo_output.dataout
		full  : out std_logic;                                         --            .full
		empty : out std_logic                                          --            .empty
	);
end entity fifo320;

architecture rtl of fifo320 is
	component fifo320_fifo_181_hlc74wy_cmp is
		port (
			data  : in  std_logic_vector(319 downto 0) := (others => 'X'); -- datain
			wrreq : in  std_logic                      := 'X';             -- wrreq
			rdreq : in  std_logic                      := 'X';             -- rdreq
			clock : in  std_logic                      := 'X';             -- clk
			aclr  : in  std_logic                      := 'X';             -- aclr
			q     : out std_logic_vector(319 downto 0);                    -- dataout
			full  : out std_logic;                                         -- full
			empty : out std_logic                                          -- empty
		);
	end component fifo320_fifo_181_hlc74wy_cmp;

	for fifo_0 : fifo320_fifo_181_hlc74wy_cmp
		use entity fifo_181.fifo320_fifo_181_hlc74wy;
begin

	fifo_0 : component fifo320_fifo_181_hlc74wy_cmp
		port map (
			data  => data,  --  fifo_input.datain
			wrreq => wrreq, --            .wrreq
			rdreq => rdreq, --            .rdreq
			clock => clock, --            .clk
			aclr  => aclr,  --            .aclr
			q     => q,     -- fifo_output.dataout
			full  => full,  --            .full
			empty => empty  --            .empty
		);

end architecture rtl; -- of fifo320
