// dpram_32bit_64.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module dpram_32bit_64 (
		input  wire [31:0] data,      //      data.datain
		output wire [31:0] q,         //         q.dataout
		input  wire [5:0]  wraddress, // wraddress.wraddress
		input  wire [5:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	dpram_32bit_64_ram_2port_181_vmsfvsy ram_2port_0 (
		.data      (data),      //   input,  width = 32,      data.datain
		.q         (q),         //  output,  width = 32,         q.dataout
		.wraddress (wraddress), //   input,   width = 6, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 6, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
