// xgmii5g_fifo.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module xgmii5g_fifo (
		input  wire [71:0] data,    //  fifo_input.datain
		input  wire        wrreq,   //            .wrreq
		input  wire        rdreq,   //            .rdreq
		input  wire        wrclk,   //            .wrclk
		input  wire        rdclk,   //            .rdclk
		output wire [71:0] q,       // fifo_output.dataout
		output wire        rdempty  //            .rdempty
	);

	xgmii5g_fifo_fifo_181_6h3aqba fifo_0 (
		.data    (data),    //   input,  width = 72,  fifo_input.datain
		.wrreq   (wrreq),   //   input,   width = 1,            .wrreq
		.rdreq   (rdreq),   //   input,   width = 1,            .rdreq
		.wrclk   (wrclk),   //   input,   width = 1,            .wrclk
		.rdclk   (rdclk),   //   input,   width = 1,            .rdclk
		.q       (q),       //  output,  width = 72, fifo_output.dataout
		.rdempty (rdempty)  //  output,   width = 1,            .rdempty
	);

endmodule
