// serdes_reset.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module serdes_reset (
		input  wire       clock,              //              clock.clk
		input  wire       reset,              //              reset.reset
		output wire [0:0] pll_powerdown,      //      pll_powerdown.pll_powerdown
		output wire [1:0] tx_analogreset,     //     tx_analogreset.tx_analogreset
		output wire [1:0] tx_digitalreset,    //    tx_digitalreset.tx_digitalreset
		output wire [1:0] tx_ready,           //           tx_ready.tx_ready
		input  wire [0:0] pll_locked,         //         pll_locked.pll_locked
		input  wire [1:0] pll_select,         //         pll_select.pll_select
		input  wire [1:0] tx_cal_busy,        //        tx_cal_busy.tx_cal_busy
		input  wire [0:0] pll_cal_busy,       //       pll_cal_busy.pll_cal_busy
		output wire [1:0] rx_analogreset,     //     rx_analogreset.rx_analogreset
		output wire [1:0] rx_digitalreset,    //    rx_digitalreset.rx_digitalreset
		output wire [1:0] rx_ready,           //           rx_ready.rx_ready
		input  wire [1:0] rx_is_lockedtodata, // rx_is_lockedtodata.rx_is_lockedtodata
		input  wire [1:0] rx_cal_busy         //        rx_cal_busy.rx_cal_busy
	);

	altera_xcvr_reset_control #(
		.CHANNELS              (2),
		.PLLS                  (1),
		.SYS_CLK_IN_MHZ        (125),
		.SYNCHRONIZE_RESET     (1),
		.REDUCED_SIM_TIME      (1),
		.TX_PLL_ENABLE         (1),
		.T_PLL_POWERDOWN       (71000),
		.SYNCHRONIZE_PLL_RESET (1),
		.TX_ENABLE             (1),
		.TX_PER_CHANNEL        (1),
		.T_TX_ANALOGRESET      (70000),
		.T_TX_DIGITALRESET     (70020),
		.T_PLL_LOCK_HYST       (70000),
		.EN_PLL_CAL_BUSY       (1),
		.RX_ENABLE             (1),
		.RX_PER_CHANNEL        (1),
		.T_RX_ANALOGRESET      (70040),
		.T_RX_DIGITALRESET     (74000)
	) xcvr_reset_control_0 (
		.clock              (clock),              //   input,  width = 1,              clock.clk
		.reset              (reset),              //   input,  width = 1,              reset.reset
		.pll_powerdown      (pll_powerdown),      //  output,  width = 1,      pll_powerdown.pll_powerdown
		.tx_analogreset     (tx_analogreset),     //  output,  width = 2,     tx_analogreset.tx_analogreset
		.tx_digitalreset    (tx_digitalreset),    //  output,  width = 2,    tx_digitalreset.tx_digitalreset
		.tx_ready           (tx_ready),           //  output,  width = 2,           tx_ready.tx_ready
		.pll_locked         (pll_locked),         //   input,  width = 1,         pll_locked.pll_locked
		.pll_select         (pll_select),         //   input,  width = 2,         pll_select.pll_select
		.tx_cal_busy        (tx_cal_busy),        //   input,  width = 2,        tx_cal_busy.tx_cal_busy
		.pll_cal_busy       (pll_cal_busy),       //   input,  width = 1,       pll_cal_busy.pll_cal_busy
		.rx_analogreset     (rx_analogreset),     //  output,  width = 2,     rx_analogreset.rx_analogreset
		.rx_digitalreset    (rx_digitalreset),    //  output,  width = 2,    rx_digitalreset.rx_digitalreset
		.rx_ready           (rx_ready),           //  output,  width = 2,           rx_ready.rx_ready
		.rx_is_lockedtodata (rx_is_lockedtodata), //   input,  width = 2, rx_is_lockedtodata.rx_is_lockedtodata
		.rx_cal_busy        (rx_cal_busy),        //   input,  width = 2,        rx_cal_busy.rx_cal_busy
		.tx_manual          (2'b00),              // (terminated),                                
		.rx_manual          (2'b00),              // (terminated),                                
		.tx_digitalreset_or (2'b00),              // (terminated),                                
		.rx_digitalreset_or (2'b00)               // (terminated),                                
	);

endmodule
