// up_data_dpram_8x4096.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module up_data_dpram_8x4096 (
		input  wire [7:0]  data_a,    //    data_a.datain_a
		output wire [7:0]  q_a,       //       q_a.dataout_a
		input  wire [7:0]  data_b,    //    data_b.datain_b
		output wire [7:0]  q_b,       //       q_b.dataout_b
		input  wire [11:0] address_a, // address_a.address_a
		input  wire [11:0] address_b, // address_b.address_b
		input  wire        wren_a,    //    wren_a.wren_a
		input  wire        wren_b,    //    wren_b.wren_b
		input  wire        clock_a,   //   clock_a.clk
		input  wire        clock_b    //   clock_b.clk
	);

	up_data_dpram_8x4096_ram_2port_181_kxenyxq ram_2port_0 (
		.data_a    (data_a),    //   input,   width = 8,    data_a.datain_a
		.q_a       (q_a),       //  output,   width = 8,       q_a.dataout_a
		.data_b    (data_b),    //   input,   width = 8,    data_b.datain_b
		.q_b       (q_b),       //  output,   width = 8,       q_b.dataout_b
		.address_a (address_a), //   input,  width = 12, address_a.address_a
		.address_b (address_b), //   input,  width = 12, address_b.address_b
		.wren_a    (wren_a),    //   input,   width = 1,    wren_a.wren_a
		.wren_b    (wren_b),    //   input,   width = 1,    wren_b.wren_b
		.clock_a   (clock_a),   //   input,   width = 1,   clock_a.clk
		.clock_b   (clock_b)    //   input,   width = 1,   clock_b.clk
	);

endmodule
