// ddr_wrmask_dpram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module ddr_wrmask_dpram (
		input  wire [39:0] data,            //            data.datain
		output wire [39:0] q,               //               q.dataout
		input  wire [8:0]  wraddress,       //       wraddress.wraddress
		input  wire [8:0]  rdaddress,       //       rdaddress.rdaddress
		input  wire        wren,            //            wren.wren
		input  wire        wrclock,         //         wrclock.clk
		input  wire        rdclock,         //         rdclock.clk
		input  wire        rden,            //            rden.rden
		input  wire        rd_addressstall, // rd_addressstall.rd_addressstall
		input  wire        rdinclocken,     //     rdinclocken.rdinclocken
		input  wire        rdoutclocken     //    rdoutclocken.rdoutclocken
	);

	ddr_wrmask_dpram_ram_2port_181_s2lz7ka ram_2port_0 (
		.data            (data),            //   input,  width = 40,            data.datain
		.q               (q),               //  output,  width = 40,               q.dataout
		.wraddress       (wraddress),       //   input,   width = 9,       wraddress.wraddress
		.rdaddress       (rdaddress),       //   input,   width = 9,       rdaddress.rdaddress
		.wren            (wren),            //   input,   width = 1,            wren.wren
		.wrclock         (wrclock),         //   input,   width = 1,         wrclock.clk
		.rdclock         (rdclock),         //   input,   width = 1,         rdclock.clk
		.rden            (rden),            //   input,   width = 1,            rden.rden
		.rd_addressstall (rd_addressstall), //   input,   width = 1, rd_addressstall.rd_addressstall
		.rdinclocken     (rdinclocken),     //   input,   width = 1,     rdinclocken.rdinclocken
		.rdoutclocken    (rdoutclocken)     //   input,   width = 1,    rdoutclocken.rdoutclocken
	);

endmodule
