// txParam_dram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module txParam_dram (
		input  wire [72:0] data,      //      data.datain
		output wire [72:0] q,         //         q.dataout
		input  wire [8:0]  wraddress, // wraddress.wraddress
		input  wire [8:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	txParam_dram_ram_2port_181_ekolvbi ram_2port_0 (
		.data      (data),      //   input,  width = 73,      data.datain
		.q         (q),         //  output,  width = 73,         q.dataout
		.wraddress (wraddress), //   input,   width = 9, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 9, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
