// vsyncinfo_ram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module vsyncinfo_ram (
		input  wire [63:0] data,      //      data.datain
		output wire [63:0] q,         //         q.dataout
		input  wire [4:0]  wraddress, // wraddress.wraddress
		input  wire [4:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        wrclock,   //   wrclock.clk
		input  wire        rdclock    //   rdclock.clk
	);

	vsyncinfo_ram_ram_2port_181_jxtf3dy ram_2port_0 (
		.data      (data),      //   input,  width = 64,      data.datain
		.q         (q),         //  output,  width = 64,         q.dataout
		.wraddress (wraddress), //   input,   width = 5, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 5, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,   width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,   width = 1,   rdclock.clk
	);

endmodule
