// shutter_wrbuff_dpram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module shutter_wrbuff_dpram (
		input  wire [63:0] data,      //      data.datain
		output wire [63:0] q,         //         q.dataout
		input  wire [8:0]  wraddress, // wraddress.wraddress
		input  wire [8:0]  rdaddress, // rdaddress.rdaddress
		input  wire        wren,      //      wren.wren
		input  wire        clock      //     clock.clk
	);

	shutter_wrbuff_dpram_ram_2port_181_7e2g3qi ram_2port_0 (
		.data      (data),      //   input,  width = 64,      data.datain
		.q         (q),         //  output,  width = 64,         q.dataout
		.wraddress (wraddress), //   input,   width = 9, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 9, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock)      //   input,   width = 1,     clock.clk
	);

endmodule
